# For local development only.

version: '3'

services:
  zephir-7.4:
    container_name: phalcon-zephir-7.4
    hostname: zephir-74
    build: docker/7.4
    working_dir: /srv
    environment:
      - "USER=Zephir"
    volumes:
      - .:/srv
      - /d/ProjectZephir/php-to-zephir/bin/converted/phpgrid/phpgrid:/srv/phpgrid
      - /d/ProjectZephir/php-to-zephir/bin/converted/phpgrid/config.json:/srv/config.json

  zephir-8.0:
    container_name: phalcon-zephir-8.0
    hostname: zephir-80
    build: docker/8.0
    working_dir: /srv
    environment:
      - "USER=Zephir"
    volumes:
      - .:/srv
      - /d/ProjectZephir/php-to-zephir/bin/converted/phpgrid/phpgrid:/srv/phpgrid
      - /d/ProjectZephir/php-to-zephir/bin/converted/phpgrid/config.json:/srv/config.json

  # zephir-8.1:
  #   container_name: phalcon-zephir-8.1
  #   hostname: zephir-81
  #   build: docker/8.1
  #   working_dir: /srv
  #   environment:
  #     - "USER=Zephir"
  #   volumes:
  #     - .:/srv
